import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import ExcelJS from 'exceljs';
import { initializeRoleWorkspace } from '../scripts/initialize-role-workspace.mjs';
import { createPendingAction, applyConfirmedAction } from '../scripts/apply-confirmed-action.mjs';
import { setCurrentRole } from '../scripts/agent-state.mjs';
import { getRoleSnapshot } from '../scripts/get-role-snapshot.mjs';
const pipeline = { stages: [{id:0,name:'简历初筛'},{id:1,name:'业务一面'},{id:2,name:'业务二面'},{id:3,name:'Offer'},{id:4,name:'入职'}] };
test('concurrent initialization cannot delete the successful workspace',async t=>{const rootPath=await fs.mkdtemp(path.join(os.tmpdir(),'init-race-'));t.after(()=>fs.rm(rootPath,{recursive:true,force:true}));const args={rootPath,roleName:'岗位',pipeline,capacity:2};const results=await Promise.allSettled([initializeRoleWorkspace(args),initializeRoleWorkspace(args)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await fs.access(path.join(rootPath,'workflow','roles','岗位','candidate-ledger.xlsx'));assert.match(await fs.readFile(path.join(rootPath,'workflow','roles','岗位','招聘数据复盘.html'),'utf8'),/AUTO_LEDGER_DATA/);});
const documents = Object.fromEntries(['CONTEXT.md','ROLE_STANDARD.md','SOURCING_STRATEGY.md','KEYWORD_ITERATIONS.md','FEEDBACK_ITERATIONS.md'].map(n=>[n, n === 'CONTEXT.md' ? '# 已确认\n当前标准版本：v1\n' : '# 已确认内容\n']));
async function setup(t) { const rootPath=await fs.mkdtemp(path.join(os.tmpdir(),'repair-core-')); t.after(()=>fs.rm(rootPath,{recursive:true,force:true})); const {rolePath}=await initializeRoleWorkspace({rootPath,roleName:'岗位',pipeline,capacity:5,documents}); return {rootPath,rolePath}; }
function proposal(overrides={}) {return {role:'岗位',intent:'candidate_create',candidate:{id:'C-001',name:'甲'},changes:[{field:'主阶段',after:'0-简历初筛'},{field:'阶段状态',after:'进行中'},{field:'简历来源',after:'员工推荐'},{field:'简历收取时间',after:'2026-09-01'}],evidence:[],...overrides};}
test('candidate IDs cannot alias the same archive by letter case',async t=>{const {rootPath,rolePath}=await setup(t);const first=await createPendingAction({rootPath,proposal:proposal()});await applyConfirmedAction({rootPath,proposalId:first.id});const next=await createPendingAction({rootPath,proposal:proposal({candidate:{id:'c-001',name:'乙'}})});await assert.rejects(applyConfirmedAction({rootPath,proposalId:next.id}),/大小写|重复/);assert.equal((await fs.readdir(path.join(rolePath,'candidates'))).length,1);});
async function editLedger(rolePath, callback) { const w=new ExcelJS.Workbook(); const p=path.join(rolePath,'candidate-ledger.xlsx'); await w.xlsx.readFile(p); const s=w.getWorksheet('候选人台账'); const ix=new Map(s.getRow(3).values.slice(1).map((v,i)=>[v,i+1])); callback(s,ix); await w.xlsx.writeFile(p); }
test('rejects portable traversal and reserved proposal/candidate IDs',async t=>{const {rootPath}=await setup(t); for(const id of ['../escape','..\\escape','CON','aux.txt','bad:stream','trailing.']) {await assert.rejects(()=>createPendingAction({rootPath,proposal:proposal({id})}),/不合法|非法|safe/i); await assert.rejects(()=>createPendingAction({rootPath,proposal:proposal({candidate:{id,name:'甲'}})}),/不合法|非法|safe/i);}});
test('proposal IDs cannot overwrite earlier confirmation previews',async t=>{const {rootPath}=await setup(t); await createPendingAction({rootPath,proposal:proposal({id:'fixed'})}); await assert.rejects(()=>createPendingAction({rootPath,proposal:proposal({id:'fixed'})}),/已存在|重复/);});
test('apply rejects current-role mismatch and changed proposal contents',async t=>{const {rootPath}=await setup(t); const p=await createPendingAction({rootPath,proposal:proposal()}); await setCurrentRole({rootPath,role:'另一岗位'}); await assert.rejects(()=>applyConfirmedAction({rootPath,proposalId:p.id}),/当前岗位|选择/); await setCurrentRole({rootPath,role:'岗位'}); p.candidate.name='被篡改'; await fs.writeFile(path.join(rootPath,'.recruitment-agent','pending-actions',`${p.id}.json`),JSON.stringify(p)); await assert.rejects(()=>applyConfirmedAction({rootPath,proposalId:p.id}),/变化|变更|篡改|预览/);});
test('older previews are stale after another preview for same role',async t=>{const {rootPath}=await setup(t);const a=await createPendingAction({rootPath,proposal:proposal()}); await createPendingAction({rootPath,proposal:proposal({candidate:{id:'C-002',name:'乙'}})});await assert.rejects(()=>applyConfirmedAction({rootPath,proposalId:a.id}),/最新|过期|失效|预览/);});
test('creation requires source received-date stage and status; updates require before',async t=>{const {rootPath}=await setup(t);for(const field of ['主阶段','阶段状态','简历来源','简历收取时间']) await assert.rejects(()=>createPendingAction({rootPath,proposal:proposal({changes:proposal().changes.filter(c=>c.field!==field)})}),/必须|缺少/);await assert.rejects(()=>createPendingAction({rootPath,proposal:proposal({intent:'candidate_update',changes:[{field:'备注',after:'备注'}]})}),/before/);});
test('creation preserves populated rows with missing IDs',async t=>{const {rootPath,rolePath}=await setup(t);await editLedger(rolePath,(s,ix)=>{s.getRow(4).getCell(ix.get('姓名')).value='已有候选人';s.getRow(4).getCell(ix.get('备注')).value='保留';});const p=await createPendingAction({rootPath,proposal:proposal()});await applyConfirmedAction({rootPath,proposalId:p.id});const w=new ExcelJS.Workbook();await w.xlsx.readFile(path.join(rolePath,'candidate-ledger.xlsx'));assert.equal(w.getWorksheet('候选人台账').getCell('B4').value,'已有候选人');assert.equal(w.getWorksheet('候选人台账').getCell('A5').value,'C-001');});
test('missing update candidate produces actionable error',async t=>{const {rootPath}=await setup(t);const p=await createPendingAction({rootPath,proposal:proposal({intent:'candidate_update',changes:[{field:'备注',before:'',after:'备注'}]})});await assert.rejects(()=>applyConfirmedAction({rootPath,proposalId:p.id}),/候选人.*不存在/);});
test('reopening requires explicit clearing of terminal reason',async t=>{const {rootPath,rolePath}=await setup(t);await editLedger(rolePath,(s,ix)=>{for(const [k,v] of Object.entries({'候选人ID':'C-001','姓名':'甲','主阶段':'1-业务一面','阶段状态':'终止','终止原因':'横向比较'}))s.getRow(4).getCell(ix.get(k)).value=v;});const p=await createPendingAction({rootPath,proposal:proposal({intent:'candidate_update',changes:[{field:'阶段状态',before:'终止',after:'进行中'}]})});await assert.rejects(()=>applyConfirmedAction({rootPath,proposalId:p.id}),/终止原因/);});
test('confirmed documents preserve exact content and draft placeholders are unconfirmed',async t=>{const {rootPath,rolePath}=await setup(t);assert.equal(await fs.readFile(path.join(rolePath,'CONTEXT.md'),'utf8'),documents['CONTEXT.md']);await assert.rejects(()=>initializeRoleWorkspace({rootPath,roleName:'坏岗位',pipeline,documents:{...documents,'CONTEXT.md':'{{version}}'}}),/占位|placeholder/i);await fs.writeFile(path.join(rolePath,'CONTEXT.md'),'当前标准版本：{{version}}\n');assert.equal((await getRoleSnapshot({roleName:'岗位',rolePath})).standardVersion,'待确认');});
test('snapshot counts passed intermediate and accepted Offer work, excludes completed onboarding',async t=>{const {rolePath}=await setup(t);await editLedger(rolePath,(s,ix)=>{for(const [i,stage] of ['1-业务一面','3-Offer','4-入职'].entries())for(const [k,v] of Object.entries({'候选人ID':`C-${i}`,'姓名':`${i}`,'主阶段':stage,'阶段状态':'通过','下次跟进日期':'2026-09-01'}))s.getRow(4+i).getCell(ix.get(k)).value=v;});const snapshot=await getRoleSnapshot({roleName:'岗位',rolePath,now:new Date('2026-09-08')});assert.equal(snapshot.dueFollowUps,2);assert.equal(snapshot.missingNextActions,2);});
test('previous interview feedback does not satisfy the current round',async t=>{const {rolePath}=await setup(t);await editLedger(rolePath,(s,ix)=>{for(const [k,v] of Object.entries({'候选人ID':'C-001','姓名':'甲','主阶段':'2-业务二面','阶段状态':'进行中','二面日期':'2026-09-01','面试反馈摘要':'一面：通过'}))s.getRow(4).getCell(ix.get(k)).value=v;});assert.equal((await getRoleSnapshot({roleName:'岗位',rolePath,now:new Date('2026-09-08')})).pendingFeedback,1);});
